### ISSUE TITLE
How to use Multiple MBTiles and Style.json file

### ISSUE THREAD

**Issue by toton6868** [bjornreppen/rasterize-vector-tiles#5]
I have created a Vector tile server using TileserverGL/Tessera. I have exported a few MBTiles layers through Tippecanoe. I must have to use Multiple MBTiles. Then I have designed the map through a JSON file. Now I want to create a similar design Raster Tile Server. How can I get a Raster MBTiles with a similar design?

**Comment by bjornreppen** [comment]
Unfortunately it does not yet have that kind of features. At best it can color layers based on a property or a fixed single color.  I haven't been using it for base maps, only for single layer overlays.  Apology for not having this clearly stated in the README.
